---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-projects-volume
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi
  storageClassName: harvester-longhorn
