---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-projects-volume
  namespace: automation
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
