apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: cesg-awx-backup
  namespace: automation
spec:
  deployment_name: cesg-awx
  backup_resource_requirements:
    limits:
      cpu: "4000m"
      memory: "6144Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"
