apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: cesg-awx-backup
  namespace: automation
spec:
  deployment_name: cesg-awx
  backup_resource_requirements:
    limits:
      cpu: "2000m"
      memory: "4096Mi"
    requests:
      cpu: "250m"
      memory: "64Mi"
